services:
  db:
    image: postgres:13.10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../backend/.env

  backend:
    build: ../backend
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - ../backend/.env

  frontend:
    build: ../frontend
    volumes:
      - static_volume:/app/build/
    command: sh -c "cp -r /app/build/* /static/ && exit 0"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - static_volume:/static/
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
